#!/bin/sh

SDK_STORE_URL=$(snapctl get store.url)
export SDK_STORE_URL

WORKSHOP_DEBUG=$(snapctl get workshop.debug)
export WORKSHOP_DEBUG

WORKSHOP_TEST_SNAPSHOT_CLEANUP_COOLDOWN=$(snapctl get workshop.test.snapshot-cleanup-cooldown)
export WORKSHOP_TEST_SNAPSHOT_CLEANUP_COOLDOWN

WORKSHOP_IMAGE_SERVER=$(snapctl get workshop.image.server.url)
export WORKSHOP_IMAGE_SERVER

read -r sbpid _ < /proc/self/stat
export LISTEN_PID="${sbpid}"

# shellcheck disable=SC2086
exec "$SNAP"/bin/workshopd run --create-dirs
