name: dev
base: ubuntu@24.04
sdks:
  - name: go
    channel: all/edge
  - name: project-tools
  - name: project-starter-pack
  - name: system
    plugs:
      fake-store:
        interface: tunnel
        endpoint: 8080
      sphinx-build:
        interface: tunnel
        endpoint: 8000
actions:
  docs-html: |
    make -C docs/ html
  docs-run: |
    make -C docs/ run
  docs-clean: |
    make -C docs/ clean-doc
  docs-clean-all: |
    make -C docs/ clean
  docs-check: |
    make -C docs/ {spelling,linkcheck,woke,lint-md}
  docs-upgrade: |
    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT
    make -C /project/docs clean
    rm -rf /project/docs/{Makefile,.sphinx,requirements.txt}
    rm -rf /project/.github/workflows/{automatic-doc-checks.yml,sphinx-python-dependency-build-checks.yml,markdown-style-checks.yml}
    git clone --depth 1 https://github.com/canonical/sphinx-docs-starter-pack "$TMP_DIR"
    cp -ar $TMP_DIR/docs/{Makefile,.sphinx,requirements.txt} /project/docs/
    cp -ar $TMP_DIR/.github/workflows/{automatic-doc-checks.yml,sphinx-python-dependency-build-checks.yml,markdown-style-checks.yml} /project/.github/workflows/
    cat /project/docs/requirements-dev.txt >> /project/docs/requirements.txt || true
    make -C /project/docs install
  lint: |
    golangci-lint run
    golangci-lint run --new-from-rev='HEAD~' --config=.golangci.errcheck.yaml
  shellcheck: |
    git ls-files | file --mime-type -Nnf- | grep shellscript | cut -f1 -d: | xargs shellcheck
    /opt/snapd-testing-tools/utils/spread-shellcheck tests/integration
  cover: |
    go test -covermode=count -coverpkg=./... -coverprofile=coverage.out ./...
  fake-store: |
    STORE_DIR=/tmp/sdkstore
    source tests/lib/utils.sh
    rm -rf "$STORE_DIR"
    publish_test_sdks ./tests/lib/sdk "$STORE_DIR"
    fake-gcs-server -data /tmp -backend memory -scheme http -port 8080 -host 127.0.0.1 -public-host localhost:8080
