#!/bin/bash -e

# shellcheck source=snap/local/lib/host-config
. "$SNAP/snap/lib/host-config"

configure_host refresh

# TODO: remove a one-off data -> common migration cleanup
rm -rf "${SNAP_DATA}/ssh"
rm -rf "${SNAP_DATA}/run"
