#!/bin/bash -e

# Allow the script to run without snap.
if [ -n "$SNAP" ]; then
    lib="$SNAP/snap/lib"
else
    lib="$(dirname -- "$0")/../lib"
fi

# shellcheck source=snap/local/lib/host-config
. "$lib/host-config"
# shellcheck source=snap/local/lib/lxc-utils
. "$lib/lxc-utils"

undo_configure_host

# The workshop services are stopped by the moment the remove
# hook is called. Therefore, for now, we walk the LXD projects created
# by the workshop and remove all instances/profiles/images/volumes.
projects=$(get_projects)

for p in $(echo "$projects" | xargs -L1 echo); do
    remove_instances "$p"
    remove_profiles "$p"
    remove_images "$p"
    remove_project "$p"
done

remove_network
remove_volumes
