name: Automatic tests
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
      - scratch/vm-testing
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

# Cancel currently-running builds when pushing new commits to a PR.
# Prevent TICS qserver from running concurrently.
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Call spread and unit tests as reusable workflows. This is the most
  # dependable method by which to share the artifacts
  spread:
    uses: ./.github/workflows/spread.yaml
    secrets:
      STORE_CREDENTIALS: ${{ secrets.STORE_CREDENTIALS }}
      SDKCRAFT_STORE_CREDENTIALS: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS_PROD }}
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  code-coverage:
    needs: [spread, unit-tests]
    if: github.event_name == 'schedule'
    runs-on: [self-hosted, reactive, amd64, large-tiobe, noble]
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download Coverage
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: "*code-coverage*"

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26"

      - name: Install dependencies
        run: |
          . "$GITHUB_WORKSPACE/tests/lib/retry.sh"

          retry 5 go install github.com/axw/gocov/gocov@v1.1.0
          retry 5 go install github.com/AlekSi/gocov-xml@v1.1.0
          retry 5 go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build with verbose mode on
        run: |
          . "$GITHUB_WORKSPACE/tests/lib/retry.sh"
          retry 5 go build -a -x -v ./...

      - name: Merge Coverage
        run: |
          COVERDIRS=$(find -mindepth 2 -type d -name cover | tr '\n' ',' | sed 's/.$//')
          mkdir .cover
          go tool covdata merge -i=$COVERDIRS -o .cover
          go tool covdata textfmt -i=$PWD/.cover -o coverage.out
          gocov convert coverage.out > coverage.json
          # coverage.xml must be in a .coverage folder.
          mkdir .coverage
          gocov-xml < coverage.json > .coverage/coverage.xml

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@333078bc527399e5916a166bd1a3a788be5a01a9 # v3.12.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }} # zizmor: ignore[secrets-outside-env]
          project: workshop
          installTics: true
