name: LXD Candidate Check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  spread:
    uses: ./.github/workflows/spread.yaml
    with:
      lxd_channel: 6/candidate
    secrets:
      SDKCRAFT_STORE_CREDENTIALS: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS_PROD }}
