name: Release
on:
  push:
    tags:
      - 'v[0-9]*'

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  verify-tag:
    environment: release
    permissions:
      contents: read
    runs-on:
      - self-hosted
      - Linux
      - noble
      - X64
      - medium
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Verify signed tag
        env:
          MAINTAINERS_SSH_PUBKEYS: ${{ vars.MAINTAINERS_SSH_PUBKEYS }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "$MAINTAINERS_SSH_PUBKEYS" > "$RUNNER_TEMP/allowed_signers"
          git config gpg.ssh.allowedSignersFile "$RUNNER_TEMP/allowed_signers"
          git config gpg.format ssh
          git verify-tag "$TAG_NAME"

  build:
    needs: verify-tag
    permissions:
      contents: read
    strategy:
      matrix:
        runner:
          - arch: ARM64
          - arch: X64
    runs-on:
      - self-hosted
      - Linux
      - noble
      - ${{ matrix.runner.arch }}
      - medium
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: canonical/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1.3.0
        id: snapcraft

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: snap-${{ matrix.runner.arch }}
          path: ${{ steps.snapcraft.outputs.snap }}

      - uses: canonical/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40 # v1.2.0
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: stable

  create-release:
    needs: build
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - Linux
      - noble
      - X64
      - medium
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: snap-*
          path: snaps
          merge-multiple: true

      - run: |
          gh release create --repo "$GITHUB_REPOSITORY" --notes-file=- "$TAG_NAME" snaps/*.snap <<EOF
          See [release notes](https://ubuntu.com/workshop/docs/release-notes/$TAG_NAME/).
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
